<?php
set_include_path('/home/lsolesen/workspace/konstrukt-fork/lib/' . PATH_SEPARATOR . get_include_path());
require_once 'app.php';

function konstrukt_menu()
{
    return array(
        'konstrukt' => array(
            'title' => 'Konstrukt',
            'page callback' => 'konstrukt_show_view',
            'access arguments' => array('access content'),
            'type' => MENU_CALLBACK,
        ),
    );
}

function konstrukt_show_view()
{
    global $base_path;
     
    $href_base = $base_path; // must not trailing slash or include hostname
    $href_base = substr($href_base, 0, -1);
    $request_uri = '/' . str_replace($base_path . '/konstrukt', '', request_uri());
 
    ob_start();
    k()->setContext(new k_HttpRequest($href_base, $request_uri, null, new MyLanguageLoader(), new SimpleTranslatorLoader()))->run('Root')->out();
    ob_end_flush();
    return ob_get_contents();
}
